version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: devtask-backend
    restart: unless-stopped
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: mydatabase
      MONGO_USER: myuser
      MONGO_PASSWORD: mypassword
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8083:8083"
    volumes:
      - ./backend:/code
    networks:
      - devtask-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8083  # ✅ Use localhost for browser access
    container_name: devtask-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:4173"
    command: npm run preview
    networks:
      - devtask-net

  mongo:
    image: mongo:6.0
    container_name: my_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - devtask-volume:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mydatabase --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  devtask-volume:

networks:
  devtask-net:
