- name: Force delete mongo-debug pod via shell
  shell: |
    kubectl delete pod mongo-debug -n devtask --grace-period=0 --force || true
  changed_when: true

- name: Wait until mongo-debug pod is fully deleted (shell check)
  shell: |
    kubectl get pod mongo-debug -n devtask --no-headers || echo "gone"
  register: pod_check
  until: '"gone" in pod_check.stdout'
  retries: 10
  delay: 2
  changed_when: false

- name: Deploy debug pod for MongoDB connectivity check
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: mongo-debug
        namespace: devtask
        labels:
          app: mongo-debug
      spec:
        restartPolicy: Never
        containers:
          - name: debug
            image: mongo:4.4.6
            command: ["sleep", "3600"]

- name: Wait for debug pod to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: devtask
    name: mongo-debug
  register: mongo_debug_status
  until: mongo_debug_status.resources[0].status.phase == "Running"
  retries: 5
  delay: 5

- name: Exec into debug pod to check MongoDB connectivity
  kubernetes.core.k8s_exec:
    namespace: devtask
    pod: mongo-debug
    command:
      - mongosh
      - --host
      - mongodb-service
      - --eval
      - "db.runCommand({ ping: 1 })"
  register: mongo_ping
  retries: 3
  delay: 3
  until: "'ok' in mongo_ping.stdout"

- name: Show MongoDB ping result
  debug:
    var: mongo_ping.stdout

- name: Auto-delete mongo-debug pod after health check
  shell: |
    kubectl delete pod mongo-debug -n devtask --grace-period=0 --force || true
  changed_when: true
